// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  pricing: dynamic(() => import("./Pricing")),
  recent_work: dynamic(() => import("./RecentWork")),
  section_columns: dynamic(() => import("./SectionColumns")),
  testimonial: dynamic(() => import("./Testimonial")),
  what_we_do: dynamic(() => import("./WhatWeDo")),
};
