// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cta_button: dynamic(() => import("./CtaButton")),
  hero: dynamic(() => import("./Hero")),
};
