// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  case_studies: dynamic(() => import("./CaseStudies")),
  hero: dynamic(() => import("./Hero")),
  recent_work: dynamic(() => import("./RecentWork")),
  section_columns: dynamic(() => import("./SectionColumns")),
};
